services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy-config:/config
      - caddy-data:/data
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}

volumes:
  caddy-config:
  caddy-data:
